<?php

namespace AppBundle\Repository;

/**
 * BaseContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseContentRepository extends \Doctrine\ORM\EntityRepository
{
}
