<?php

namespace AppBundle\Repository;

/**
 * ConceptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptRepository extends \Doctrine\ORM\EntityRepository
{
}
