<?php

namespace AppBundle\Repository;

/**
 * FooterImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FooterImageRepository extends \Doctrine\ORM\EntityRepository
{
}
