<?php

namespace AppBundle\Repository;

/**
 * FooterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FooterRepository extends \Doctrine\ORM\EntityRepository
{
}
