<?php

namespace AppBundle\Repository;

/**
 * PortFolioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortFolioRepository extends \Doctrine\ORM\EntityRepository
{
}
